{
  "global": {
    "cache_dir": "/home/amir/\u0414\u043e\u043a\u0443\u043c\u0435\u043d\u0442\u044b/PROJECTS/mcp/CODEX/projcet_blabla/.agents/codex-subagents/cache",
    "logs_dir": "/home/amir/\u0414\u043e\u043a\u0443\u043c\u0435\u043d\u0442\u044b/PROJECTS/mcp/CODEX/projcet_blabla/.agents/codex-subagents/logs",
    "runtime_state": "/home/amir/\u0414\u043e\u043a\u0443\u043c\u0435\u043d\u0442\u044b/PROJECTS/mcp/CODEX/projcet_blabla/.agents/codex-subagents/runtime_state.json",
    "tasks_dir": "/home/amir/\u0414\u043e\u043a\u0443\u043c\u0435\u043d\u0442\u044b/PROJECTS/mcp/CODEX/projcet_blabla/.agents/codex-subagents/tasks"
  },
  "agents": {}
}
